"use client"
import { Container, CardContainer } from './styles'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Container>
      <CardContainer>
        {children}
      </CardContainer>
    </Container>
  )
}
